---
title: "bactcountr"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE)
```

```{r message= FALSE}
library(devtools)
#devtools::install_github("aef1004/bactcountr")

library(shiny)
library(openxlsx)
library(flexdashboard)
library(readxl)
library(DT)
library(bactcountr)
library(ggpubr)
library(dplyr)
library(rstatix)
library(tidyr)
```

Input {.sidebar}
-----------------------------------------------------------------------
```{r}
inputPanel(
  fileInput("formatted_data", label = "Data Upload")
)


```

Raw Metadata
-----------------------------------------------------------------------
```{r error = FALSE, message = FALSE, warning = FALSE}

metadata <- reactive({
   read_xlsx(input$formatted_data$datapath, sheet = "metadata") %>%
    as.data.frame()
})

DT::renderDataTable({
    metadata()
})

```

Cleaned CFU Data
-----------------------------------------------------------------------
```{r}
# Use this one with the pick_dilution

# CFU_data <- reactive({
#    read_xlsx(input$formatted_data$datapath, sheet = "CFU_data") %>%
#     as.data.frame()%>%
#   tidy_CFU() %>%
#   pick_one_dilution("CFUs", c("group", "replicate"))  %>%
#   calculate_cfu(dilution_factor = metadata()$dilution_factor,
#                 resuspend_volume_ml = metadata()$resuspend_volume, 
#                 volume_plated_uL = metadata()$volume_plated,
#                 percent = metadata()$percent_organ, "dilution", "CFUs") 
# })

# this one is for finding the average of groups
CFU_data <- reactive({
   read_xlsx(input$formatted_data$datapath, sheet = "CFU_data") %>%
    as.data.frame()%>%
  tidy_CFU() %>%
  calculate_cfu(dilution_factor = metadata()$dilution_factor,
                resuspend_volume_ml = metadata()$resuspend_volume, 
                volume_plated_uL = metadata()$volume_plated,
                percent = metadata()$percent_organ, "dilution", "CFUs") %>%
    select(-log_CFUs) %>%
  filter(CFUs != 0) %>%
  group_by(group, replicate) %>%
  mutate(log_CFUs = log10(whole_CFUs),
         average_log_CFUs = log10(mean(whole_CFUs)),
         variance = log10(var(whole_CFUs)),
         standard_deviation = log10(sd(whole_CFUs))) %>%
    arrange(group, replicate) %>%
    ungroup()
})

DT::renderDataTable({
    CFU_data()
})

inputPanel(
  downloadButton("wb", "Download Cleaned Data")
)


# output the excel file with both of the data structures
output$wb <- downloadHandler(
  filename = function() {
    paste0("cleaned_CFU", "_data", ".xlsx")
  },
  content = function(file) {
    write.xlsx(list(metat_data = metadata(),
                    CFU_data = CFU_data()), file)
  }
)
```

Group Averages
-----------------------------------------------------------------------
```{r}
group_data <- reactive({
   CFU_data() %>%
    select(group, whole_CFUs) %>%
    group_by(group) %>%
      mutate(average_log_CFUs = log10(mean(whole_CFUs)),
         variance = log10(var(whole_CFUs)),
         standard_deviation = log10(sd(whole_CFUs))) %>%
    select(-whole_CFUs) %>%
      unique()
    
})

DT::renderDataTable({
    group_data()
})

 inputPanel(
   downloadButton("gpdata", "Download Group Averages")
 ) 
 
 #output the excel file with both of the data structures
 output$gpdata <- downloadHandler(
   filename = function() {
     paste0("group_averages", ".xlsx")
   },
   content = function(file) {
     write.xlsx(group_data(), file)
   }
 )
```

Plots
-----------------------------------------------------------------------

```{r}
inputPanel(
  selectInput("stat_analysis", label = "Statistical Analysis", 
              choices = c("none", "t test", "Anova and Tukey HSD"))
)


tukey_sig <- reactive({
 CFU_data() %>%
    ungroup() %>%
    select(group, log_CFUs) %>%
    mutate(group = as.factor(group)) %>%
    aov(log_CFUs ~ group, data = .) %>%
    TukeyHSD() %>%
    broom::tidy() %>%
    separate(col = "contrast", c("group1", "group2"), sep = "-") %>%
    filter(adj.p.value < 0.05) %>%
    mutate(adj.p.value   = round(adj.p.value, 3)) %>%
    mutate(star = "*")
}) 



tukey_ypos <- reactive({
  c(max(max(abs(tukey_sig()$conf.low)), max(abs(tukey_sig()$conf.high))))
})


t_sig <- reactive({
  CFU_data() %>%
    ungroup() %>%
    select(group, log_CFUs) %>%
    unique() %>%
    t_test(log_CFUs ~ group) %>% #   adjust_pvalue(method = "BH") %>%
    add_significance() 
   #rstatix::add_xy_position(x = "group")
  })


t_ypos <- reactive({
  c(max(abs(t_sig()$statistic)))
})


name_of_plot <- reactive({
  paste(metadata()$exp_name, "D", metadata()$timepoint, metadata()$sample_type, "CFUs")
})


uiOutput("dynamic")

output$dynamic <- renderUI({
  if(input$stat_analysis == "Anova and Tukey HSD"){
    plotOutput("anova_plot")}
    else if (input$stat_analysis == "none"){
      plotOutput("plot")}
  else{plotOutput("t_plot")}
  })

#  no stats
output$plot <- renderPlot({
  ggbarplot(x = "group", y = "log_CFUs", fill = "group", alpha = 0.5, data = CFU_data(),
       font.label = list(size = 30, face = "plain"), add = c("mean_se")) +
  ggtitle(paste("No stats", name_of_plot()))
})

# t-test
output$t_plot <- renderPlot({
  ggbarplot(x = "group", y = "log_CFUs", fill = "group", alpha = 0.5, data = CFU_data(),
       font.label = list(size = 30, face = "plain"), add = c("mean_se")) +
      stat_pvalue_manual(data = t_sig(), hide.ns = TRUE, y.position = t_ypos(), step.increase = 0.1) +
    ggtitle(paste("T-test", name_of_plot()))
})

# Anova and Tukey HSD
output$anova_plot <- renderPlot({
  ggbarplot(x = "group", y = "log_CFUs", fill = "group", alpha = 0.5, data = CFU_data(),
       font.label = list(size = 30, face = "plain"), add = c("mean_se")) +
  stat_pvalue_manual(data = tukey_sig(), label = "star", hide.ns = TRUE, y.position = tukey_ypos(), step.increase = 0.1) +
  ggtitle(paste("Anova and Tukey", name_of_plot()))
})
```

