---
title: "bactcountr Shiny App"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

# google reactive drop down menu
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(shiny)
library(flexdashboard)
library(DT)
library(janitor)
library(openxlsx)
```

Input {.sidebar}
-----------------------------------------------------------------------

```{r}

inputPanel(
  textInput("exp_name", label = "Experiment Name", value = ""),
  
  numericInput("timepoint", label = "Timepoint in Days", value = "0"),
  
  dateInput("plating_date", label = "Date Plated", value = Sys.Date()),
  
  dateInput("counting_date", label = "Date Counted", value = Sys.Date()),
  
  selectInput("sample_type", label = "Sample Type", choices = c("Culture","Lung", "Spleen",
                                                                "BoneMarrow", "BAL")),
  
  numericInput("dilution_factor", label = "Dilution Factor", value = ""),
  
  numericInput("resuspend_volume", label = "Resuspend Volume in mL", value = ""),
  
  numericInput("volume_plated", label = "Volume Plated in uL", value = ""),
  
  numericInput("percent_organ", label = "Percent of Organ as decimal", value = ""),
  
  sliderInput("dilutions_plated", label = "Dilutions Plated", min = 0, max = 11, 
              value =c(0, 7)),
  
  downloadButton("wb", "Download")
)
```


Outputs
-----------------------------------------------------------------------

### Metadata Output

```{r}

metadata <- reactive({ 
    data.frame(exp_name = input$exp_name, 
               timepoint = input$timepoint,
               plating_date = input$plating_date,
               counting_date = input$counting_date,
               sample_type = input$sample_type,
               dilution_factor = input$dilution_factor,
               resuspend_volume = input$resuspend_volume,
               volume_plated = input$volume_plated,
               percent_organ = input$percent_organ,
               min_dilution_plated = input$dilutions_plated[1],
               max_dilution_plated = input$dilutions_plated[2])
  })

DT::renderDataTable({
    metadata()
})



```


### CFU File Output


```{r}

CFU_data <- reactive({ 
  
  all_dilutions <- c(input$dilutions_plated[1]:input$dilutions_plated[2])
  dilution_colnames <- paste("dilution", all_dilutions, sep = "_")
    
  group = NA # have to do this so that the data frame can be made with empty rows
  replicate = NA

  z= c("group", "replicate", dilution_colnames)
    
  data.frame(matrix(vector(), 50, length(z),
                    dimnames=list(c(), z)),
                    stringsAsFactors=F)
    
  })


output[["table"]] <- DT::renderDT(CFU_data(), selection ='none', server = TRUE, editable = 'all')
DTOutput("table")


```


```{r}
# output the excel file with both of the data structures
output$wb <- downloadHandler(
  filename = function() {
    paste0(input$exp_name, "_D", input$timepoint, "_", input$sample_type, "_CFU", "_data", ".xlsx")
  },
  content = function(file) {
    write.xlsx(list(metadata = metadata(), 
                    CFU_data = CFU_data()), file)
  }
)
```


