---
title: "try_matrix"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(flexdashboard)
library(DT)
library(janitor)
library(openxlsx)
library(shinyMatrix)
```

Input {.sidebar}
-----------------------------------------------------------------------

```{r}

inputPanel(
  textInput("exp_name", label = "Experiment Name", value = ""),
  
  numericInput("timepoint", label = "Timepoint in Days", value = "0"),
  
  dateInput("plating_date", label = "Date Plated", value = Sys.Date()),
  
  dateInput("counting_date", label = "Date Counted", value = Sys.Date()),
  
  selectInput("organ", label = "Organ", choices = c("Lung", "Spleen", "BoneMarrow", "BAL")),
  
  numericInput("dilution_factor", label = "Dilution Factor", value = ""),
  
  numericInput("resuspend_volume", label = "Resuspend Volume in mL", value = ""),
  
  numericInput("volume_plated", label = "Volume Plated in uL", value = ""),
  
  numericInput("percent_organ", label = "Percent of Organ as decimal", value = ""),
  
  sliderInput("dilutions_plated", label = "Dilutions Plated", min = 0, max = 10, value =c(0, 8)),
  
  downloadButton("wb", "Download")
)
```


Outputs
-----------------------------------------------------------------------

### Metadata Output

```{r}

metadata <- reactive({ 
    data.frame(exp_name = input$exp_name, 
               timepoint = input$timepoint,
               plating_date = input$plating_date,
               counting_date = input$counting_date,
               organ = input$organ,
               dilution_factor = input$dilution_factor,
               resuspend_volume = input$resuspend_volume,
               volume_plated = input$volume_plated,
               percent_organ = input$percent_organ,
               min_dilution_plated = input$dilutions_plated[1],
               max_dilution_plated = input$dilutions_plated[2])
  })

m <- matrix(runif(12), 6, 2, dimnames = list(NULL, c("x", "y")))

matrixInput(
  inputId = "sample", 
  value = m,
  #inputClass = matrix-input,
  rows = list(extend = TRUE), 
  cols = list(names = TRUE),
  class = "numeric",
  paste = TRUE,
  copy = TRUE
)


renderPlot({
  plot(input$sample, col = "red", main = "Scatterplot")
})

```
