---
title: "bactcountr Shiny App"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(shiny)
library(flexdashboard)
```


## Input

```{r}

inputPanel(
  textInput("exp_name", label = "Experiment Name", value = ""),
  
  numericInput("timepoint", label = "Timepoint in Days", value = ""),
  
  dateInput("plating_date", label = "Date Plated", value = ""),
  
  dateInput("counting_date", label = "Date Counted", value = Sys.Date()),
  
  selectInput("organ", label = "Organ", choices = c("Lung", "Spleen", "BoneMarrow", "BAL")),
  
  numericInput("dilution_factor", label = "Dilution Factor", value = ""),
  
  numericInput("resuspend_volume", label = "Resuspend Volume in mL", value = ""),
  
  numericInput("volume_plated", label = "Volume Plated in uL", value = ""),
  
  numericInput("percent_organ", label = "Percent of Organ", value = ""),
  
  sliderInput("dilutions_plated", label = "Dilutions Plated", min = 0, max = 10, value =c(0, 8))

)
```


```{r}

```




